import { Rokkitt } from 'next/font/google';
import './globals.css';
import { EventProvider } from '@/context/EventProvider';

const rokkitt = Rokkitt({ subsets: ['latin'] });

export const metadata = {
  title: 'Tech Udbhav',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rokkitt.className}>
        <EventProvider>{children}</EventProvider>
      </body>
    </html>
  );
}
